# Generated by Django 2.1.7 on 2019-03-04 21:11

import CC.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=CC.models.current_year)),
                ('language', models.CharField(max_length=20)),
                ('number', models.IntegerField(help_text='Count of songs', verbose_name='#')),
            ],
        ),
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='CC.artist')),
            ],
        ),
        migrations.CreateModel(
            name='cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Cover')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CC.artist')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='', verbose_name='Cover of Genre')),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('mp3', models.FileField(help_text='Music mp3 file', upload_to='Sounds/', verbose_name='MP3')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CC.album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CC.artist')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CC.cover')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.genre')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CC.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.genre'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('artist', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'title')},
        ),
    ]
