# Generated by Django 2.1.7 on 2019-03-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='img',
            field=models.ImageField(upload_to='Covers/', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='CC.artist'),
        ),
    ]
