# Generated by Django 2.1.7 on 2019-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0002_auto_20190305_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistimg',
            name='img',
            field=models.ImageField(upload_to='artist/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='img',
            field=models.ImageField(upload_to='genreCover/', verbose_name='Cover of Genre'),
        ),
    ]
