# Generated by Django 2.1.7 on 2019-03-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0003_auto_20190305_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
